smart_bulbs:
  - name: Desk Lamp
    device_id: YOUR_DEVICE_ID
    address: YOUR_DEVICE_IP_ADDRESS
    local_key: YOUR_DEVICE_LOCAL_KEY
    version: 3.4
  - name: Bedside Lamp
    device_id: ANOTHER_DEVICE_ID
    address: ANOTHER_DEVICE_IP_ADDRESS
    local_key: ANOTHER_DEVICE_LOCAL_KEY
    version: 3.4

pomodoros:
  - name: classic
    duration: 25
    short_break: 5
    long_break: 15
    cycles_before_long_break: 4
  - name: blitz
    duration: 15
    short_break: 3
    long_break: 10
    cycles_before_long_break: 3

themes:
  - name: simple-work
    work:
      color: [ 255, 255, 255 ]
      saturation: 1000
      brightness: 1000
      temperature: 1000
    short_break:
      color: [ 0, 0, 0 ]
      saturation: 1000
      brightness: 1000
      temperature: 1000
    long_break:
      color: [ 0, 0, 0 ]
      saturation: 1000
      brightness: 1000
      temperature: 1000
  - name: anime
    work:
      color: [ 0, 0, 0 ]
      saturation: 1000
      brightness: 1000
      temperature: 1000
    short_break:
      color: [ 255, 255, 255 ]
      saturation: 1000
      brightness: 1000
      temperature: 1000
    long_break:
      color: [ 255, 255, 255 ]
      saturation: 1000
      brightness: 1000
      temperature: 1000
  - name: cozzy
    work:
      color: [ 255, 255, 0 ]
      saturation: 600
      brightness: 300
      temperature: 1000
    short_break:
      duration: 5
      color: [ 0, 0, 0 ]
      saturation: 1000
      brightness: 1000
      temperature: 1000
    long_break:
      duration: 15
      color: [ 0, 0, 0 ]
      saturation: 1000
      brightness: 1000
      temperature: 1000
